name: ROS Workflow

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  pull_request:

jobs:
  formatblack:
    name: Style Check Code with Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."

      - name: Annotate diff changes using reviewdog
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: blackfmt

      - name: Fail if actions taken
        if: steps.action_black.outputs.is_formatted == 'true'
        run: exit 1
